### PR TITLE
Merge pull request #1 from frida-magola/develop

### PR DESCRIPTION
**Pull request by frida-magola**
Develop

### CODE REVIEW

**Review by eunice-kat — COMMENTED** [review]
https://github.com/994707367/Calculatrice-.git

**Review by eunice-kat — COMMENTED** [review]
https://github.com/994707367/Calculatrice-.git

**Comment by corneillek243** [comment]
# Création et demande de variables
a = int(input("Entrez le 1er N° : "))
b = int(input("Entrez le 2ᵉ N° : "))

op = input("Entrez l'opérateur (+, -, *, /) : ")

if op == "+":
    print("a + b =", a + b)
elif op == "-":
    print("a - b =", a - b)
elif op == "*":
    print("a * b =", a * b)
elif op == "/":
    if b != 0:
        print("a / b =", a / b)
    else:
        print("Erreur : Division par zéro")
else:
    print("Opérateur invalide")

**Comment by kanyimbuilunga** [comment]
https://github.com/kanyimbuilunga/Programme-retrait-et-d-p-t-argent-.git

**Comment by eunice-kat** [comment]
https://github.com/eunice-kat/Depot-retrait.git

**Comment by Rosiekasuka** [comment]
Main.py(1)

**Comment by Aaron533-alt** [comment]
https://github.com/Aaron533-alt/Airtel.git

**Comment by AimeranceKakenge** [comment]
https://github.com/AimeranceKakenge/D-p-t-d-argent-.git

**Comment by Deb216** [comment]
https://github.com/Deb216/D-p-t-.git

**Comment by thomasdiur** [comment]
https://github.com/thomasdiur/Retrait-d-argent-.git

**Comment by Pacificateur24** [comment]
https://github.com/Pacificateur24/Airtel-moyen-.git

**Comment by thomasdiur** [comment]
https://github.com/thomasdiur/Retrait-d-argent.git

**Comment by B883151** [comment]
https://github.com/B883151/Programme--depot-retrait.git

**Comment by thomasdiur** [comment]
https://github.com/thomasdiur/Index.html.git

**Comment by ChristianBanza** [comment]
https://github.com/ChristianBanza/Index.html.git

**Comment by ChristianBanza** [comment]
https://github.com/ChristianBanza/Index.ht.git

**Comment by Rosiekasuka** [comment]
https://github.com/Rosiekasuka/Exercise-en-JavaScript.git

**Comment by Bles868** [comment]
https://github.com/Bles868/exercices-en-java.git

**Comment by AimeranceKakenge** [comment]
https://github.com/AimeranceKakenge/Exercice-JS.git

**Comment by Feruzi2000** [comment]
https://github.com/Feruzi2000/Exercice-Javascript.git

**Comment by eunice-kat** [comment]
https://github.com/eunice-kat/Index.htm.git

**Comment by eunice-kat** [comment]
https://github.com/eunice-kat/Exercice-en-JavaScript-.git

**Comment by japhetkabimb19** [comment]
https://github.com/japhetkabimb19/Exercice-Javascript.git

**Comment by JeanMwepu** [comment]
https://github.com/JeanMwepu/Tp.git

**Comment by JeanMwepu** [comment]
https://github.com/JeanMwepu/Calculatrice.git

**Comment by bukasacharlotte0** [comment]
https://github.com/bukasacharlotte0/Projet-pratique-2-java.git

**Comment by JeanMwepu** [comment]
https://github.com/JeanMwepu/Projet-2-java.git

**Comment by levis097** [comment]
https://github.com/levis097/Exercice-en-java.git

**Comment by ChristianBanza** [comment]
https://github.com/ChristianBanza/Projet-restaurant-.git

**Comment by eunice-kat** [comment]
https://github.com/eunice-kat/Projet-restaurant-.git

**Comment by vanelianne090** [comment]
https://github.com/vanelianne090/Java-2.git

**Comment by Prince-Herbert2005** [comment]
https://github.com/Prince-Herbert2005/Projet-.git

**Comment by Pacificateur24** [comment]
https://github.com/Pacificateur24/Restaurant-.git

**Comment by Pacificateur24** [comment]
https://github.com/Pacificateur24/PT-JavaScript-.git

**Comment by snowdenweb** [comment]
https://github.com/snowdenweb/Restaurant-.git

**Comment by corneillek243** [comment]
https://github.com/corneillek243/Exercice-java-2.git

**Comment by snowdenweb** [comment]
https://github.com/snowdenweb/JavaScript-.git

**Comment by Rosiekasuka** [comment]
https://github.com/Rosiekasuka/Exercise.git

**Comment by thomasdiur** [comment]
Menucommande.java

**Comment by thomasdiur** [comment]
https://github.com/thomasdiur/Menu.git

**Comment by AimeranceKakenge** [comment]
restaurant.java

**Comment by AimeranceKakenge** [comment]
https://github.com/AimeranceKakenge/Restaurant.java-exercice/blob/3e962026f1016b5951909fd6856afceb90cf7fe3/restaurant.java

**Comment by AimeranceKakenge** [comment]
https://github.com/AimeranceKakenge/Restaurant.java-exercice.git

**Pull request merged**
